services:
  nginx:
    image: nginx:1.28.0
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  memcached:
    image: memcached:1.6.30
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4